### ISSUE TITLE
Implementera fuzzy search med Fuse.js 

### ISSUE THREAD

**Issue by BenTroyCahoon** [Fannynystrom/movieflix#10]
Integrera Fuse.js för fuzzy search-funktionalitet. Integrera Fuse.js för fuzzy sökning. Implementera sökfältet och gör så att resultaten visas dynamiskt under sökningen.

**Comment by AdamAxsson** [comment]
Searchbar tillagd

**Comment by AdamAxsson** [comment]
5 tester tillagda

**Comment by AdamAxsson** [comment]
-Behov av ytterliggare styling
-Behov av Filmview sida för att redirectas vid onclick av film

**Comment by AdamAxsson** [comment]
Annars klar
