### ISSUE TITLE
 Förbättring av pull request-granskningar

### ISSUE THREAD

**Issue by Fannynystrom** [Fannynystrom/movieflix#21]
Vi behöver alla bli bättre på att noggrant granska pull requests innan de godkänns. Det är viktigt att koden är väl dokumenterad och att förändringar är tydligt beskrivna, särskilt om vi inte har visat eller förklarat för varandra vad ändringarna innebär.

**Comment by idacaesar** [comment]
Kolla EXTRA noga i pull request efter .env filen och mapp namnen så att det är med små bokstäver
