### ISSUE TITLE
Tester för Bookmarked

### ISSUE THREAD

**Issue by Fannynystrom** [Fannynystrom/movieflix#37]
Testa med mockad data: 

Att meddelande "Du har inga bokmärkta filmer" visas när inga bokmärkta filmer finns

Lägga till i bokmärke

Ta bort i bokmärke 

Att localStorage uppdateras när du tar bort/lägger till i bokmärke

**Comment by BenTroyCahoon** [comment]
Ändrade koden så den körs med vitest.
