### ISSUE TITLE
Testingdelen: "Förnekla/optimera"-MovieCard test.

### ISSUE THREAD

**Issue by BenTroyCahoon** [Fannynystrom/movieflix#65]
Ändra om Moviecard-testet. Se till att använda mindre mocks.

**Comment by AdamAxsson** [comment]
Klar?

**Comment by BenTroyCahoon** [comment]
Japp. som fasiken ! VI hade ändrat lite routes samt tagit bort dropdown-menyn med synopsis mm och istället ordnat en snygg modal som visar mer film info osv. Testerna fick skrivas om för denna funktionalitet samt la till att den testar "screenview" för mobil t.ex/B
